### PR TITLE
Feat/markdown linting

### PR DESCRIPTION
**Pull request by theantichris**

### CODE REVIEW

**Review by ryexley — DISMISSED** [review]
I would approve this, but the new integrated action for linting the markdown is failing because of a linting error. We should probably correct the issue before merging this in I think.

**Comment by theantichris** [comment]
```
README.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 113]
README.md:17:113 MD047/single-trailing-newline Files should end with a single newline character
Error: Process completed with exit code 1.
```

Yes, it is and I'll fix it. The weird thing here is I have VSC set to add that line on save and I didn't see this error before pushing.

**Comment by theantichris** [comment]
@ryexley Ok, it looks like I have my action setup weird because the lint is failing for @Thomas-Jean 's branch.

1. @Thomas-Jean will need to fix the README in his branch (or tell me what rules to adjust)
1. I need to fix my GitHub action to only lint the current branch

**Comment by theantichris** [comment]
> @ryexley Ok, it looks like I have my action setup weird because the lint is failing for @Thomas-Jean 's branch.
> 
> 1. @Thomas-Jean will need to fix the README in his branch (or tell me what rules to adjust)
> 2. I need to fix my GitHub action to only lint the current branch

Scratch all that. I think I need to rebase on develop and fix it.

**Review by ryexley — APPROVED** [review]

**Pull request merged**
