### PR TITLE
fix: add note of needed rebase

### PR DESCRIPTION
**Pull request by Thomas-Jean**

### CODE REVIEW

**Review by ryexley — DISMISSED** [review]
Non-blocking, but I might expand on this message just a little bit to add some explanation for _why_ this needs to be done. I only say that because this is an important step. Especially if/when we bring junior devs on board, it'll be helpful for them to know why this needs to be done.

**Comment by theantichris** [comment]
> Non-blocking, but I might expand on this message just a little bit to add some explanation for _why_ this needs to be done. I only say that because this is an important step. Especially if/when we bring junior devs on board, it'll be helpful for them to know why this needs to be done.

I agree. Often the "why" is much more important to document than the "how".

**Review by theantichris — CHANGES_REQUESTED** [review]
Document why please.

**Review by ryexley — APPROVED** [review]
👌 :shipit:

**Review by theantichris — APPROVED** [review]

**Pull request merged**
